runtime: go116

# Note: this is interpreted by gae.py, it maps the app ID being deployed to
# values of ${...} vars.
# Reference: https://chromium.googlesource.com/infra/luci/luci-go/+/HEAD/examples/appengine/helloworld_v2/app.yaml
luci_gae_vars:
  gofindit-dev:
    AUTH_SERVICE_HOST: chrome-infra-auth-dev.appspot.com
  gofindit:
    AUTH_SERVICE_HOST: chrome-infra-auth.appspot.com

handlers:
- url: /.*
  script: auto
  secure: always

entrypoint: >
  main
  -auth-service-host ${AUTH_SERVICE_HOST}