runtime: python27
api_version: 1
threadsafe: true


handlers:
- url: /_ah/spi/.*
  secure: always
  script: main.APPLICATION

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
  secure: always

- url: /bower_components
  static_dir: static/bower_components
  secure: always

- url: /images
  static_dir: static/images
  secure: always

- url: /styles
  static_dir: static/styles
  secure: always

- url: /elements
  static_dir: static/elements
  secure: always

- url: /js
  static_dir: static/js
  secure: always

- url: /
  static_files: static/html/index.html
  upload: static/html/index\.html
  secure: always

- url: /stats.*
  script: google.appengine.ext.appstats.ui.app

- url: /tasks/clean_outdated_graphs
  login: admin
  script: main.WEBAPP

- url: /timeseries_update
  secure: always
  script: main.WEBAPP

libraries:
- name: endpoints
  version: 1.0
- name: jinja2
  version: latest
- name: pycrypto
  version: "2.6"
- name: webapp2
  version: latest
- name: webob
  version: "1.2.3"

includes:
- components/auth

builtins:
- appstats: on

skip_files:
- ^(.*/)?.*~
