runtime: python27
api_version: 1
threadsafe: true


handlers:

- url: /_ah/spi/.*
  secure: always
  script: main.APPLICATION

- url: /bower_components
  secure: always
  static_dir: bower_components

- url: /elements
  secure: always
  static_dir: elements

- url: /js
  secure: always
  static_dir: js

- url: /styles
  secure: always
  static_dir: styles

- url: /images
  secure: always
  static_dir: images

- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico
  secure: always

- url: /
  static_files: html/index.html
  upload: html/index\.html
  secure: always

libraries:
- name: endpoints
  version: 1.0
- name: jinja2
  version: latest
- name: pycrypto
  version: "2.6"
- name: webapp2
  version: latest
- name: webob
  version: "1.2.3"

includes:
- components/auth

skip_files:
- ^(.*/)?.*~
