runtime: python27
api_version: 1
threadsafe: true

# Edit this to match your implementation.
handlers:

- url: /bower_components
  static_dir: bower_components

- url: /elements
  static_dir: elements

- url: /js
  static_dir: js

- url: /styles
  static_dir: styles

- url: /images
  static_dir: images

- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico
  secure: always

- url: /
  static_files: html/index.html
  upload: html/index\.html

libraries:
- name: endpoints
  version: 1.0
- name: jinja2
  version: latest
- name: pycrypto
  version: "2.6"
- name: webapp2
  version: latest
- name: webob
  version: "1.2.3"

includes:
- components/auth

skip_files:
- ^(.*/)?.*~