application: findit-for-waterfall
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /_ah/pipeline(/.*)?
  script: "pipeline_utils.appengine_third_party_pipeline_src_pipeline.\
           handlers._APP"
  secure: always

- url: /.*
  script: main.application
  secure: always

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
