application: findit-for-waterfall
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
  - remote_api: on

handlers:
# Pipeline handler.
- url: /_ah/pipeline(/.*)?
  script: "pipeline_utils.appengine_third_party_pipeline_src_pipeline.\
           handlers._APP"
  secure: always

# Endpoints handler.
- url: /_ah/spi/.*
  script: main.api_application
  secure: always

- url: /.*
  script: main.web_application
  secure: always

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0
