application: findit-for-waterfall
version: 1
runtime: python27
api_version: 1
threadsafe: true
instance_class: F1
automatic_scaling:
  min_idle_instances: 1

builtins:
  - remote_api: on

handlers:
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /
  static_files: templates/home.html
  upload: templates/home.html

# Pipeline status UI handler.
- url: /_ah/pipeline(/.*)?
  script: main.pipeline_status_application
  secure: always

# Endpoints handler.
- url: /_ah/spi/.*
  script: main.api_application
  secure: always

- url: /.*
  script: main.web_application
  secure: always

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*_test\.py$
- ^(.*/)?tests\.py$
- ^(.*/)?\..*$
- ^(.*/)?.*\.md$
- ^(.*/)?README$
- ^(.*/)?Makefile$
- ^(.*/)?util_scripts/.*$

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0
