runtime: python27
api_version: 1
threadsafe: true

# Edit this to match your implementation.
handlers:
- url: /_ah/spi/.*
  secure: always
  script: main.APPLICATION

libraries:
- name: endpoints
  version: 1.0
- name: jinja2
  version: latest
- name: pycrypto
  version: "2.6"
- name: webapp2
  version: latest
- name: webob
  version: "1.2.3"

includes:
- components/auth
