runtime: go111

env_variables:
  PROD_ENV: "staging"

handlers:
  - url: /images
    static_dir: images
    secure: always

  - url: /css
    static_dir: css
    secure: always

  - url: /static/dist
    static_dir: static/dist
    secure: always

  - url: /cron/.*
    script: auto
    login: admin

  - url: /
    script: auto
    secure: always

  - url: /.*
    script: auto
    secure: always
