application: tricium-dev
module: gerrit-reporter
runtime: go
api_version: go1

handlers:

- url: /internal.*
  script: _go_app
  secure: always
  login: admin

- url: /gerrit-reporter/queue
  script: _go_app
  secure: always
  login: admin

- url: /.*
  script: _go_app
  secure: always
