runtime: go
api_version: go1

handlers:
# For static resources such as css and js files.
- url: /static
  secure: always
  static_dir: static

# For admin resources or endpoints meant to be hit by a cron job.
- url: /admin/.*
  script: _go_app
  secure: always
  login: admin

# Everything goes here.
- url: /.*
  script: _go_app
  secure: always

builtins:
- remote_api: on
