application: unnamed-ci
module: default
version: 1
runtime: python27
instance_class: F1
api_version: 1
threadsafe: true

automatic_scaling:
  min_idle_instances: 5
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: 30ms
  max_concurrent_requests: 50

handlers:
- url: /.*
  script: app.log.log.app
  secure: always

- url: /api/v1/job.*
  script: app.api.job.app
  secure: always

- url: /api/v1/worker.*
  script: app.api.worker.app
  secure: always

builtins:
- remote_api: on

libraries:
- name: webapp2
  version: latest

skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?\..*
- ^tests.*
- ^tools.*
- ^(.*/)?.*\.orig
- ^(.*/)?.*\.rej
- ^[A-Z]+
- ^[A-Z]+\.[a-z]+
