application: chromium-status-hr
version: 1
runtime: python27
api_version: 1
threadsafe: false

inbound_services:
- warmup
- xmpp_message

handlers:
- url: /(.*\.(html|js))
  static_files: static/\1
  upload: static/(.*\.(html|js))

# main will look for a replacement in blobstore, if not, will redirect to
# static/
- url: /([^/]+\.(gif|png|jpg|ico))
  script: main.APPLICATION

- url: /static/([^/]+\.(gif|png|jpg|ico))
  static_files: static/\1
  upload: static/([^/]+\.(gif|png|jpg|ico))

- url: /stylesheets
  static_dir: stylesheets

- url: /templates
  script: templates

- url: /restricted/.*
  script: main.APPLICATION
  login: admin

- url: /.*
  script: main.APPLICATION


# Search DEFAULT_SKIP_FILES in google.appengine.api.appinfo plus a few others
skip_files: |
    ^(.*/)?(
    (app\.yaml)|
    (app\.yml)|
    (index\.yaml)|
    (index\.yml)|
    (#.*#)|
    (.*~)|
    (.*\.py[co])|
    (.*/RCS/.*)|
    (\..*)|
    (tests/.*)|
    (tools/.*)|
    ([A-Z]+(\.py)?)|
    (Makefile)|
    (.*\.rej)|
    (.*\.orig)|
    )$
