application: chromiumcodereview-hr
version: use-version-arg
runtime: python27
api_version: 1
threadsafe: false

default_expiration: 7d  # This is good for images, which never change

# The commented "secure: always" handler can't be enabled for appspot.com
# applications with a custom domain, since GAE doesn't support HTTPS on custom
# domains at the moment.
handlers:

- url: /(robots.txt|favicon.ico)
  static_files: static/\1
  upload: static/(robots.txt|favicon.ico)

- url: /google7db36eb2cc527940.html
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /static/upload.py
  script: main.application
#  secure: always

- url: /static/(script.js|styles.css)
  static_files: static/\1
  upload: static/(script.js|styles.css)
  expiration: 1h  # Shorter expiration, these change often
#  secure: always

- url: /static
  static_dir: static
#  secure: always

# URL of schedules tasks.  See cron.yaml.
- url: /restricted/.*
  script: main.application
  login: admin

- url: /tasks/migrate_entities
  script: main.application
  login: admin

# Before uploading, do:
#
# svn co http://appengine-mapreduce.googlecode.com/svn/trunk/python/src/mapreduce
#
#- url: /mapreduce(/.*)?
#  script: mapreduce/main.py
#  login: admin

- url: /.*
  script: main.application
#  secure: always

admin_console:
  pages:
  - name: Client ID and Secret Settings
    url: /admin/set-client-id-and-secret

inbound_services:
- mail
- xmpp_message
- warmup

builtins:
- appstats: on
#- deferred: on
- remote_api: on

libraries:
- name: django
  version: 1.3

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'
