application: chromium-status
version: 1
runtime: python
api_version: 1

inbound_services:
- xmpp_message

handlers:
- url: /(.*\.(gif|png|jpg|ico|html|js))
  static_files: static/\1
  upload: static/(.*\.(html|js|gif|png|jpg|ico))

- url: /stylesheets
  static_dir: stylesheets

- url: /templates
  script: templates

- url: /.*
  script: main.py
