application: tricium-dev
module: gerrit-poller
runtime: go
api_version: go1

handlers:

- url: /internal.*
  script: _go_app
  secure: always
  login: admin

- url: /gerrit-poller/internal/.*
  script: _go_app
  secure: always
  login: admin

- url: /.*
  script: _go_app
  secure: always
