application: cr-rev
version: 1
runtime: python27
api_version: 1
threadsafe: true
module: default
instance_class: F1
automatic_scaling:
  min_idle_instances: 1

handlers:
# Endpoints handler.
- url: /_ah/spi/.*
  script: appengine.cr_rev.cr_rev_api.APPLICATION
  secure: always

- url: /css
  static_dir: appengine/cr_rev/css
  secure: always

- url: /.*
  script: appengine.cr_rev.app.app
  secure: always

builtins:
- remote_api: on

inbound_services:
- warmup

libraries:
- name: jinja2
  version: latest
- name: endpoints
  version: 1.0
- name: numpy
  version: latest
