application: test-results-hrd
version: 1
runtime: python27
api_version: 1
threadsafe: true
instance_class: F4

builtins:
- appstats: on

handlers:
- url: /appengine_module/components
  static_dir: appengine_module/components

- url: /testfile/delete
  script: appengine_module.test_results.main.app
  login: admin

- url: /.*
  script: appengine_module.test_results.main.app

- url: /updatebuilders
  script: appengine_module.test_results.main.app
  login: admin

- url: /internal/monitoring/upload
  script: appengine_module.test_results.main.app
  login: admin
  secure: always
