application: test-results-hrd
module: python
runtime: python27
api_version: 1
threadsafe: true
instance_class: F4

handlers:
- url: /internal/monitoring/upload
  script: appengine_module.test_results.main.app
  login: admin
  secure: always
