cron:
- description: LUCI config datastore cache periodic refresh
  url: /admin/config/cache/manager
  schedule: every 10 minutes
- description: Device config data periodic refresh
  url: /internal/cron/sync-dev-config
  schedule: every 1 hours
- description: Manufacturing config data periodic refresh
  url: /internal/cron/sync-manufacturing-config
  schedule: every 1 hours
- description: Inventory change history periodic dump to bigquery
  url: /internal/cron/changehistory-to-bq
  schedule: every 10 minutes
- description: Push inventory to drone queen
  url: /internal/cron/push-to-drone-queen
  schedule: every 10 minutes

- description: Compare iventory from V1 and V2
  url: /internal/cron/compare-inventory
  schedule: every 24 hours

- description: report metrics of Duts in inventory.
  url: /internal/cron/report-inventory
  schedule: every 5 minutes
