cron:
- description: LUCI config datastore cache periodic refresh
  url: /admin/config/cache/manager
  schedule: every 10 minutes
- description: Device config data periodic refresh
  url: /internal/cron/sync-dev-config
  schedule: every 1 hours
