application: tree-status
runtime: go
api_version: go1

handlers:
- url: /elements
  static_dir: elements
  secure: always

- url: /images
  static_dir: images
  secure: always

- url: /bower_components
  static_dir: bower_components
  secure: always

- url: /.*
  script: _go_app
  secure: always

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^node_modules$
- ^bower_components/web-component-tester$
- ^bower_components/accessibility-developer-tools$
- ^bower_components/async$
- ^bower_components/chai$
- ^bower_components/lodash$
- ^bower_components/mocha$
- ^bower_components/sinon-chai$
- ^bower_components/sinonjs$
- ^bower_components/stacky$
- ^bower_components/test-fixture$
