application: test-results-hrd
module: default
runtime: go
api_version: go1
instance_class: F4_1G
automatic_scaling:
  max_concurrent_requests: 4

handlers:
  - url: /robots.txt
    static_files: static/robots.txt
    upload: static/robots.txt

  - url: /images
    static_dir: static/images

  - url: /stylesheets
    static_dir: static/stylesheets

  - url: /dashboards
    static_dir: static/dashboards

  - url: /src
    static_dir: src

  - url: /bower_components
    static_dir: bower_components

  - url: /internal/.*
    script: _go_app
    login: admin
    secure: always

  - url: /.*
    script: _go_app
