application: test-results-hrd
module: default
runtime: go
api_version: go1
instance_class: F4_1G
automatic_scaling:
  max_concurrent_requests: 4

handlers:
  - url: /robots.txt
    static_files: static/robots.txt
    upload: static/robots.txt

  - url: /images
    static_dir: static/images

  - url: /stylesheets
    static_dir: static/stylesheets

  - url: /dashboards
    static_dir: static/dashboards

  - url: /components
    static_dir: components

  - url: /bower_components
    static_dir: bower_components

  - url: /testfile/uploadform
    static_files: static/pages/uploadform.html
    upload: static/pages/uploadform.html
    mime_type: text/html; charset=utf-8

  - url: /.*
    script: _go_app
