runtime: python27
api_version: 1
threadsafe: true

# Edit this to match your implementation.
handlers:
- url: /.*
  secure: always
  script: main.app

libraries:
- name: endpoints
  version: 1.0
- name: jinja2
  version: latest
- name: pycrypto
  version: "2.6"
- name: webapp2
  version: latest
- name: webob
  version: "1.2.3"

includes:
- gae_ts_mon  # handles /internal/cron/ts_mon/send
