application: chrome-infra-packages-dev
module: default
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /_ah/spi/.*
  script: apps.endpoints_app

- url: /internal.*
  script: apps.frontend_app
  secure: always
  login: admin

- url: /static/html/
  static_dir: static/html/
  secure: always

- url: /static/images/
  static_dir: static/images/
  secure: always

# Note: the vulcanized version of the frontend doesn't need all of the
# source files here but appengine doesn't support conditional stanzas.
- url: /static/
  static_dir: static/
  secure: always

- url: /
  static_files: static/html/index-vulcanized.html
  upload: static/html/index-vulcanized.html
  secure: always

- url: /.*
  script: apps.frontend_app
  secure: always

builtins:
- remote_api: on

includes:
- components/auth
- components/ereporter2
- components/static_third_party.yaml

libraries:
- name: endpoints
  version: "1.0"
- name: jinja2
  version: "2.6"
- name: pycrypto
  version: "2.6"
- name: webapp2
  version: "2.5.2"
- name: webob
  version: "1.2.3"
- name: yaml
  version: "3.10"

skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*\.orig
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*\.rej
- ^(.*/)?.*~
- ^(.*/)?\..*
- ^(.*/)?test.*
- ^[A-Z]+
- ^[A-Z]+\.[a-z]+
- ^tools.*
