application: sheriff-o-matic
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
# API Endpoints.
- url: /alerts
  script: alerts.app
  secure: always

- url: /alerts-history
  script: alerts.app
  secure: always

- url: /alerts-history/.*
  script: alerts.app
  secure: always

- url: /internal-alerts
  script: internal_alerts.app
  secure: always

# Static resources.
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
  secure: always

- url: /images
  static_dir: images
  secure: always

- url: /lib
  static_dir: lib
  secure: always

- url: /model
  static_dir: model
  secure: always

- url: /scripts
  static_dir: scripts
  secure: always

- url: /styles
  static_dir: styles
  secure: always

- url: /ui
  static_dir: ui
  secure: always

- url: /bower_components
  static_dir: bower_components
  secure: always

# Application root.
- url: /.*
  static_files: sheriff-o-matic.html
  upload: sheriff-o-matic.html
  secure: always
  http_headers:
      Strict-Transport-Security: max-age=10886400; includeSubDomains

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*_test\.py$
- ^(.*/)?tests\.py$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?.*\.md$
- ^(.*/)?LICENSE$
- ^(.*/)?README$
- ^(.*/)?Makefile$

libraries:
- name: webapp2
  version: "latest"
