runtime: go
env: flex
api_version: go1
service: api
instance_class: F1


handlers:
- url: /.*
  script: _go_app
  secure: always

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
