application: cr-build-dev
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static/
  static_dir: static_files/
  secure: always

- url: /favicon.ico
  static_files: static_files/favicon.ico
  upload: static_files/favicon.ico
  secure: always

- url: /.*
  script: main.app
  login: required
  secure: always

libraries:
- name: endpoints
  version: 1.0
- name: jinja2
  version: latest
- name: webapp2
  version: latest

builtins:
- deferred: on
- remote_api: on

skip_files:
- ^(.*/)?.*\.(orig|rej|py[co])
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?\..*
- ^tests.*
- ^[A-Z]+(\.[a-z]+)?
