application: gsbypass
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- deferred: on

handlers:
- url: /.*
  script: gsbypass.app
  secure: always
  login: required

libraries:
- name: jinja2
  version: latest
- name: markupsafe
  version: latest
