dispatch:
  - url: "*/builders"
    module: go
  - url: "*/updatebuilders"
    module: go
  - url: "*/builderstate"
    module: go
  - url: "*/updatebuilderstate"
    module: go
  - url: "*/testfile"
    module: go
  - url: "*/testfile/"
    module: go
  - url: "*/testfile/upload"
    module: go
