runtime: go
api_version: go1
instance_class: F1
service: default

handlers:
- url: /.*
  script: _go_app
  secure: always

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$

