service: default
runtime: go115

luci_gae_vars:
  chrome-fleet-karte-dev:
    AUTH_SERVICE_HOST: chrome-infra-auth-dev.appspot.com
  chrome-fleet-karte:
    AUTH_SERVICE_HOST: chrome-infra-auth.appspot.com
entrypoint: >
  main -auth-service-host ${AUTH_SERVICE_HOST}

handlers:
- url: /.*
  script: auto
  secure:  always
