runtime: go113
service: default

# Note: this is interpreted by gae.py, it maps the app ID being deployed to
# values of ${...} vars.
# Reference: https://chromium.googlesource.com/infra/luci/luci-go/+/refs/heads/master/examples/appengine/helloworld_v2/app.yaml
luci_gae_vars:
  unified-fleet-system-dev:
    AUTH_SERVICE_HOST: chrome-infra-auth-dev.appspot.com
  unified-fleet-system-staging:
    AUTH_SERVICE_HOST: chrome-infra-auth-dev.appspot.com
  unified-fleet-system-prod:
    AUTH_SERVICE_HOST: chrome-infra-auth.appspot.com

# Note: Not sure why that /usr/local/bin/start cannot be found in dev instance
# now. So temporarily running self-built go binary "ufs-service" to test.
#  /usr/local/bin/start -auth-service-host ${AUTH_SERVICE_HOST}
entrypoint: >
    ./ufs-service -auth-service-host ${AUTH_SERVICE_HOST}
