application: cr-rev
version: 1
runtime: python27
api_version: 1
threadsafe: true
module: default
automatic_scaling:
  min_idle_instances: 1

handlers:
# Endpoints handler
- url: /_ah/spi/.*
  script: cr_rev_api.APPLICATION

- url: /css
  static_dir: css
  secure: always

- url: /.*
  script: app.app
  secure: always

builtins:
- remote_api: on

inbound_services:
- warmup

libraries:
- name: jinja2
  version: latest
- name: endpoints
  version: 1.0
