application: trooper-o-matic
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- appstats: on

handlers:
- url: /images
  static_dir: images

# FIXME: Write a script to do the appcfg update so that we can error out
# # if there is no bower_components, or, even better just run "bower update".
- url: /bower_components
  static_dir: bower_components

- url: /ui
  static_dir: ui

- url: /.*
  script: main.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: numpy
  version: latest
