application: trooper-o-matic
version: 2
runtime: python27
api_version: 1
threadsafe: true

builtins:
- appstats: on

handlers:
# Endpoints handler.
- url: /_ah/spi/.*
  script: appengine_module.trooper_o_matic.trooper_o_api.APPLICATION
  secure: always

- url: /images
  static_dir: images

- url: /bower_components
  static_dir: bower_components

- url: /lib
  static_dir: lib

- url: /model
  static_dir: model

- url: /ui
  static_dir: ui

- url: /.*
  script: appengine_module.trooper_o_matic.main.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: numpy
  version: latest
- name: endpoints
  version: 1.0
