application: chromium-try-flakes
version: 9
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest

builtins:
- deferred: on
- remote_api: on