application: chromium-try-flakes
version: 19
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /issues/.*
  script: main.app
  login: admin
  secure: always
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest

builtins:
- deferred: on
- remote_api: on

instance_class: F4
automatic_scaling:
  min_idle_instances: 2
  min_pending_latency: 50ms
  max_pending_latency: 250ms

includes:
- gae_ts_mon  # handles /internal/cron/ts_mon/send
