application: tricium-dev
module: default
runtime: go
api_version: go1

handlers:

- url: /internal/.*
  script: _go_app
  secure: always
  login: admin

- url: /bower_components
  static_dir: bower_components
  secure: always

- url: /.*
  script: _go_app
  secure: always

- url: /_ah/push-handlers/.*
  script: _go_app
  secure: always
  login: admin
