application: chrome-infra-tricium-dev
module: default
runtime: go
api_version: go1

handlers:

- url: /internal/.*
  script: _go_app
  login: admin

- url: /static
  static_dir: static

- url: /.*
  script: _go_app
