application: chopsui-gallery
runtime: go
api_version: go1

handlers:
- url: /static
  static_dir: static

- url: /demo
  static_dir: demo
  secure: always

- url: /components
  static_dir: components
  secure: always

- url: /images
  static_dir: images

- url: /bower_components
  static_dir: bower_components
  secure: always

- url: /.*
  script: _go_app
  secure: always
