application: chromium-cq-status
version: 2
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on

handlers:
- url: /js
  static_dir: js
- url: /recent
  static_files: html/recent.html
  upload: html/recent.html
- url: /.*
  script: main.app


libraries:
- name: webapp2
  version: latest
- name: numpy
  version: latest
