service: default
runtime: go
api_version: go1

instance_class: F4_1G
automatic_scaling:
  max_instances: 1
  max_concurrent_requests: 80

handlers:
- url: /internal/.*
  script: _go_app
  secure: always
  login: admin
- url: /admin/.*
  script: _go_app
  secure: always
  login: admin
- url: /.*
  script: _go_app
  secure: always
