cron:
- description: LUCI config datastore cache periodic refresh
  url: /admin/config/cache/manager
  schedule: every 10 minutes

- description: tsmon house keeping
  url: /internal/cron/ts_mon/housekeeping
  schedule: every 1 minutes

- description: Refresh update time of all schedulers
  url: /internal/cron/refresh-schedulers
  schedule: every 20 minutes

- description: Flush events to bigquery tables.
  url: /internal/cron/flush-bq-events
  schedule: every 1 minutes