application: flake-predictor
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /cron/.*
  script: main.app
  login: admin
  secure: always
- url: /internal/.*
  script: main.app
  login: admin
  secure: always
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
