application: chromium-cq-status
version: 2
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on

handlers:
- url: /components
  static_dir: bower_components
- url: /scripts
  static_dir: scripts
- url: /recent.*
  static_files: recent.html
  upload: recent.html
- url: /.*
  script: appengine_module.chromium_cq_status.main.app

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?.*\.md$
- ^(.*/)?.*\.sqlite$
- ^(.*/)?LICENSE$
- ^(.*/)?README$
- ^(.*/)?Makefile$
- ^bower_components/json5/test/.*$

libraries:
- name: webapp2
  version: latest
- name: numpy
  version: latest
