runtime: go
api_version: go1
application: sheriff-o-matic-staging

handlers:
- url: /bower_components
  static_dir: bower_components
  secure: always

- url: /images
  static_dir: images
  secure: always

- url: /elements
  static_dir: elements
  secure: always

- url: /test
  static_dir: test
  secure: always

- url: /api/.*
  script: _go_app
  secure: always

- url: /_cron/.*
  script: _go_app
  secure: always
  login: admin

- url: /internal/.*
  script: _go_app
  secure: always
  login: admin

- url: /.*
  script: _go_app
  secure: always

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^node_modules$
- ^bower_components$
