application: findit-for-waterfall
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: appengine_module.findit.main.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
