# Documentation:
# https://cloud.google.com/appengine/docs/standard/go111/config/queueref
queue:
- name: result-ingestion
  rate: 500/s

- name: result-collection
  rate: 500/s

- name: update-test-variant
  rate: 500/s

- name: tq-sweep
  rate: 500/s
