# Documentation:
# https://cloud.google.com/appengine/docs/standard/go111/config/queueref
queue:
- name: result-ingestion
  rate: 500/s

- name: result-collection
  rate: 500/s

- name: update-test-variant
  rate: 500/s

- name: tq-sweep
  rate: 500/s

- name: export-test-variants
  rate: 1/s
  max_concurrent_requests: 1

- name: reclustering
  # Gradually start new tasks, so auto-scaling has time to catch-up.
  # At time of writing, ~50 workers are configured, so this ramps tasks
  # over 10 seconds.
  rate: 5/s
  retry_parameters:
    # Never retry tasks if they fail. If this is changed, reclustering run
    # progress reporting should be modified to handle shards being started
    # more than once.
    task_retry_limit: 0
