application: tricium-dev
module: gerrit
runtime: go
api_version: go1

handlers:

- url: /internal.*
  script: _go_app
  secure: always
  login: admin

- url: /gerrit/internal/.*
  script: _go_app
  secure: always
  login: admin
