cron:
- description: Update configs
  url: /admin/config/cache/manager
  schedule: every 10 minutes

- description: tsmon house keeping
  url: /internal/cron/ts_mon/housekeeping
  schedule: every 1 minutes
