application: arquebus-dev
version: 1
module: default
runtime: go
api_version: go1

handlers:
- url: /internal.*
  script: _go_app
  secure: always
  login: admin

- url: /.*
  script: _go_app
  secure: always
