cron:
- description: Update assigner configs from luci-config
  url: /internal/cron/update-assigners
  schedule: every 10 minutes

- description: Schedule Assigner runs
  url: /internal/cron/schedule-assigners
  # If the schedule of this cron changes, please also update
  # backend.model.assigner.go:scheduleAssignerCronInterval
  schedule: every 1 minutes
