name: Sync

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Sync
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git fetch https://chromium.googlesource.com/infra/infra.git main
        git merge -s ours FETCH_HEAD
        git rm -r --cached .github/
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
